#!/bin/bash
rm -f -r ~/scicomp-labs-cpp-linux/
mkdir ~/scicomp-labs-cpp-linux
git clone https://github.com/dbiersach/scicomp-labs-cpp-linux.git ~/scicomp-labs-cpp-linux
rm -f -r ~/Desktop/scicomp700/
mkdir ~/Desktop/scicomp700
git clone https://github.com/dbiersach/scicomp700-cpp-linux.git ~/Desktop/scicomp700
cp -ar ~/scicomp-labs-cpp-linux/uniform-variance/ ~/Desktop/scicomp700/session01/lab1/
cp -ar ~/scicomp-labs-cpp-linux/lrss-bubble/ ~/Desktop/scicomp700/session02/lab1/
cp -ar ~/scicomp-labs-cpp-linux/lrss-qsort/ ~/Desktop/scicomp700/session02/lab2/
cp -ar ~/scicomp-labs-cpp-linux/freq-substr/ ~/Desktop/scicomp700/session02/lab3/
cp -ar ~/scicomp-labs-cpp-linux/stoichiometry-instructor/ ~/Desktop/scicomp700/session02/lab4/
cp -ar ~/scicomp-labs-cpp-linux/draw-sphere/ ~/Desktop/scicomp700/session03/lab1/
cp -ar ~/scicomp-labs-cpp-linux/draw-torus/ ~/Desktop/scicomp700/session03/lab2/
cp -ar ~/scicomp-labs-cpp-linux/idw/ ~/Desktop/scicomp700/session03/lab3/
cp -ar ~/scicomp-labs-cpp-linux/mc-circle-prng/ ~/Desktop/scicomp700/session03/lab4/
cp -ar ~/scicomp-labs-cpp-linux/mc-circle-qrng/ ~/Desktop/scicomp700/session03/lab5/
cp -ar ~/scicomp-labs-cpp-linux/mc-sphere/ ~/Desktop/scicomp700/session03/lab6/
cp -ar ~/scicomp-labs-cpp-linux/mc-hypersphere/ ~/Desktop/scicomp700/session03/lab7/
cp -ar ~/scicomp-labs-cpp-linux/mc-highdimensional/ ~/Desktop/scicomp700/session03/lab8/
cp -ar ~/scicomp-labs-cpp-linux/projectile-motion/ ~/Desktop/scicomp700/session04/lab1/
cp -ar ~/scicomp-labs-cpp-linux/decay-fluorine18/ ~/Desktop/scicomp700/session04/lab2/
cp -ar ~/scicomp-labs-cpp-linux/decay-carbon14-instructor/ ~/Desktop/scicomp700/session04/lab3/
cp -ar ~/scicomp-labs-cpp-linux/pendulum/ ~/Desktop/scicomp700/session04/lab4/
cp -ar ~/scicomp-labs-cpp-linux/harmonograph/ ~/Desktop/scicomp700/session04/lab5/
cp -ar ~/scicomp-labs-cpp-linux/spectrum-rydberg-instructor/ ~/Desktop/scicomp700/session04/lab6/
cp -ar ~/scicomp-labs-cpp-linux/spectrum-bohr-instructor/ ~/Desktop/scicomp700/session04/lab7/
cp -ar ~/scicomp-labs-cpp-linux/list-cards-instructor/ ~/Desktop/scicomp700/session05/lab1/
cp -ar ~/scicomp-labs-cpp-linux/dealer-bogus/ ~/Desktop/scicomp700/session05/lab2/
cp -ar ~/scicomp-labs-cpp-linux/dealer-slow-instructor/ ~/Desktop/scicomp700/session05/lab3/
cp -ar ~/scicomp-labs-cpp-linux/dealer-fast/ ~/Desktop/scicomp700/session05/lab4/
cp -ar ~/scicomp-labs-cpp-linux/stdcf-encode/ ~/Desktop/scicomp700/session05/lab5/
cp -ar ~/scicomp-labs-cpp-linux/stdcf-decode-instructor/ ~/Desktop/scicomp700/session05/lab6/
cp -ar ~/scicomp-labs-cpp-linux/jenga-14/ ~/Desktop/scicomp700/session05/lab7/
cp -ar ~/scicomp-labs-cpp-linux/jenga-15-instructor/ ~/Desktop/scicomp700/session05/lab8/
cp -ar ~/scicomp-labs-cpp-linux/nyquist-known/ ~/Desktop/scicomp700/session06/lab1/
cp -ar ~/scicomp-labs-cpp-linux/nyquist-unknown/ ~/Desktop/scicomp700/session06/lab2/
cp -ar ~/scicomp-labs-cpp-linux/make-samples/ ~/Desktop/scicomp700/session06/lab3/
cp -ar ~/scicomp-labs-cpp-linux/fourier-discrete/ ~/Desktop/scicomp700/session06/lab4/
cp -ar ~/scicomp-labs-cpp-linux/space-signals/ ~/Desktop/scicomp700/session06/lab5/
cp -ar ~/scicomp-labs-cpp-linux/sunspots/ ~/Desktop/scicomp700/session06/lab6/
cp -ar ~/scicomp-labs-cpp-linux/data-binning-instructor/ ~/Desktop/scicomp700/session07/lab1/
cp -ar ~/scicomp-labs-cpp-linux/kmeans/ ~/Desktop/scicomp700/session07/lab2/
cp -ar ~/scicomp-labs-cpp-linux/parallel-simpsons/ ~/Desktop/scicomp700/session07/lab3/
