#!/bin/bash
mkdir ~/scicomp-labs-cpp-linux
git clone https://github.com/dbiersach/scicomp-labs-cpp-linux.git ~/scicomp-labs-cpp-linux
mkdir ~/Desktop/scicomp100
git clone https://github.com/dbiersach/scicomp100-cpp-linux.git ~/Desktop/scicomp100
cp -ar ~/scicomp-labs-cpp-linux/hello-world/ ~/Desktop/scicomp100/session03/lab1/
cp -ar ~/scicomp-labs-cpp-linux/age-converter/ ~/Desktop/scicomp100/session04/lab1/
cp -ar ~/scicomp-labs-cpp-linux/temperature-converter/ ~/Desktop/scicomp100/session04/lab2/
cp -ar ~/scicomp-labs-cpp-linux/gauss-sum/ ~/Desktop/scicomp100/session05/lab1/
cp -ar ~/scicomp-labs-cpp-linux/jenga-14/ ~/Desktop/scicomp100/session05/lab2/
cp -ar ~/scicomp-labs-cpp-linux/jenga-15/ ~/Desktop/scicomp100/session05/lab3/
cp -ar ~/scicomp-labs-cpp-linux/perfect-numbers/ ~/Desktop/scicomp100/session06/lab1/
cp -ar ~/scicomp-labs-cpp-linux/newton-sqrt/ ~/Desktop/scicomp100/session06/lab2/
cp -ar ~/scicomp-labs-cpp-linux/bigint-sqrt/ ~/Desktop/scicomp100/session06/lab3/
cp -ar ~/scicomp-labs-cpp-linux/hero-abilities/ ~/Desktop/scicomp100/session07/lab1/
cp -ar ~/scicomp-labs-cpp-linux/uniform-variance/ ~/Desktop/scicomp100/session07/lab2/
cp -ar ~/scicomp-labs-cpp-linux/birthday-paradox/ ~/Desktop/scicomp100/session07/lab3/
cp -ar ~/scicomp-labs-cpp-linux/basel-series/ ~/Desktop/scicomp100/session09/lab1/
cp -ar ~/scicomp-labs-cpp-linux/euclid-gcd/ ~/Desktop/scicomp100/session09/lab2/
cp -ar ~/scicomp-labs-cpp-linux/coprime-probability/ ~/Desktop/scicomp100/session09/lab3/
cp -ar ~/scicomp-labs-cpp-linux/list-cards/ ~/Desktop/scicomp100/session10/lab1/
cp -ar ~/scicomp-labs-cpp-linux/dealer-bogus/ ~/Desktop/scicomp100/session10/lab2/
cp -ar ~/scicomp-labs-cpp-linux/dealer-slow/ ~/Desktop/scicomp100/session10/lab3/
cp -ar ~/scicomp-labs-cpp-linux/dealer-fast/ ~/Desktop/scicomp100/session10/lab4/
cp -ar ~/scicomp-labs-cpp-linux/reverse-string/ ~/Desktop/scicomp100/session11/lab1/
cp -ar ~/scicomp-labs-cpp-linux/freq-plaintext/ ~/Desktop/scicomp100/session11/lab2/
cp -ar ~/scicomp-labs-cpp-linux/freq-ciphertext/ ~/Desktop/scicomp100/session11/lab3/
cp -ar ~/scicomp-labs-cpp-linux/caesar-decrypt/ ~/Desktop/scicomp100/session11/lab4/
cp -ar ~/scicomp-labs-cpp-linux/freq-bigrams/ ~/Desktop/scicomp100/session11/lab5/
cp -ar ~/scicomp-labs-cpp-linux/scramble-squares/ ~/Desktop/scicomp100/session12/lab1/
cp -ar ~/scicomp-labs-cpp-linux/draw-triangle/ ~/Desktop/scicomp100/session13/lab1/
cp -ar ~/scicomp-labs-cpp-linux/draw-rectangle/ ~/Desktop/scicomp100/session13/lab2/
cp -ar ~/scicomp-labs-cpp-linux/draw-circle/ ~/Desktop/scicomp100/session13/lab3/
cp -ar ~/scicomp-labs-cpp-linux/draw-rings/ ~/Desktop/scicomp100/session13/lab4/
cp -ar ~/scicomp-labs-cpp-linux/draw-curves/ ~/Desktop/scicomp100/session13/lab5/
cp -ar ~/scicomp-labs-cpp-linux/draw-polynomial/ ~/Desktop/scicomp100/session15/lab1/
cp -ar ~/scicomp-labs-cpp-linux/draw-monolith/ ~/Desktop/scicomp100/session15/lab2/
cp -ar ~/scicomp-labs-cpp-linux/draw-pyramid/ ~/Desktop/scicomp100/session15/lab3/
cp -ar ~/scicomp-labs-cpp-linux/draw-sphere/ ~/Desktop/scicomp100/session15/lab4/
cp -ar ~/scicomp-labs-cpp-linux/draw-torus/ ~/Desktop/scicomp100/session15/lab5/
cp -ar ~/scicomp-labs-cpp-linux/lrss-bubble/ ~/Desktop/scicomp100/session16/lab1/
cp -ar ~/scicomp-labs-cpp-linux/lrss-qsort/ ~/Desktop/scicomp100/session16/lab2/
cp -ar ~/scicomp-labs-cpp-linux/idw/ ~/Desktop/scicomp100/session16/lab3/
cp -ar ~/scicomp-labs-cpp-linux/stdcf-encode/ ~/Desktop/scicomp100/session17/lab1/
cp -ar ~/scicomp-labs-cpp-linux/stdcf-decode/ ~/Desktop/scicomp100/session17/lab2/
cp -ar ~/scicomp-labs-cpp-linux/pells-equation/ ~/Desktop/scicomp100/session17/lab3/
