#!/bin/bash
rm -f -r ~/scicomp-labs-cpp-linux/
mkdir ~/scicomp-labs-cpp-linux
git clone https://github.com/dbiersach/scicomp-labs-cpp-linux.git ~/scicomp-labs-cpp-linux
rm -f -r ~/Desktop/scicomp020/
mkdir ~/Desktop/scicomp020
git clone https://github.com/dbiersach/scicomp020-cpp-linux.git ~/Desktop/scicomp020
cp -ar ~/scicomp-labs-cpp-linux/hello-world/ ~/Desktop/scicomp020/session01/lab1/
cp -ar ~/scicomp-labs-cpp-linux/age-converter/ ~/Desktop/scicomp020/session01/lab2/
cp -ar ~/scicomp-labs-cpp-linux/temperature-converter/ ~/Desktop/scicomp020/session01/lab3/
cp -ar ~/scicomp-labs-cpp-linux/perfect-numbers/ ~/Desktop/scicomp020/session02/lab1/
cp -ar ~/scicomp-labs-cpp-linux/newton-sqrt/ ~/Desktop/scicomp020/session02/lab2/
cp -ar ~/scicomp-labs-cpp-linux/factor-quadratic/ ~/Desktop/scicomp020/session02/lab3/
cp -ar ~/scicomp-labs-cpp-linux/list-cards/ ~/Desktop/scicomp020/session03/lab1/
cp -ar ~/scicomp-labs-cpp-linux/dealer-bogus/ ~/Desktop/scicomp020/session03/lab2/
cp -ar ~/scicomp-labs-cpp-linux/dealer-slow/ ~/Desktop/scicomp020/session03/lab3/
cp -ar ~/scicomp-labs-cpp-linux/dealer-fast/ ~/Desktop/scicomp020/session03/lab4/
cp -ar ~/scicomp-labs-cpp-linux/primality-race-v1/ ~/Desktop/scicomp020/session03/lab5/
cp -ar ~/scicomp-labs-cpp-linux/circuits-logisim/ ~/Desktop/scicomp020/session04/lab2/
cp -ar ~/scicomp-labs-cpp-linux/circuits-logisim/ ~/Desktop/scicomp020/session04/lab3/
cp -ar ~/scicomp-labs-cpp-linux/basel-series/ ~/Desktop/scicomp020/session05/lab1/
cp -ar ~/scicomp-labs-cpp-linux/euclid-gcd/ ~/Desktop/scicomp020/session05/lab2/
cp -ar ~/scicomp-labs-cpp-linux/coprime-probability/ ~/Desktop/scicomp020/session05/lab3/
cp -ar ~/scicomp-labs-cpp-linux/draw-triangle/ ~/Desktop/scicomp020/session06/lab1/
cp -ar ~/scicomp-labs-cpp-linux/draw-rectangle/ ~/Desktop/scicomp020/session06/lab2/
cp -ar ~/scicomp-labs-cpp-linux/draw-circle/ ~/Desktop/scicomp020/session06/lab3/
cp -ar ~/scicomp-labs-cpp-linux/draw-rings/ ~/Desktop/scicomp020/session06/lab4/
cp -ar ~/scicomp-labs-cpp-linux/draw-curves/ ~/Desktop/scicomp020/session06/lab5/
cp -ar ~/scicomp-labs-cpp-linux/hero-abilities/ ~/Desktop/scicomp020/session07/lab1/
cp -ar ~/scicomp-labs-cpp-linux/uniform-variance/ ~/Desktop/scicomp020/session07/lab2/
cp -ar ~/scicomp-labs-cpp-linux/random-straws/ ~/Desktop/scicomp020/session07/lab3/
cp -ar ~/scicomp-labs-cpp-linux/gauss-sum/ ~/Desktop/scicomp020/session08/lab1/
cp -ar ~/scicomp-labs-cpp-linux/jenga-14/ ~/Desktop/scicomp020/session08/lab2/
cp -ar ~/scicomp-labs-cpp-linux/jenga-15/ ~/Desktop/scicomp020/session08/lab3/
cp -ar ~/scicomp-labs-cpp-linux/stdcf-encode/ ~/Desktop/scicomp020/session09/lab1/
cp -ar ~/scicomp-labs-cpp-linux/stdcf-decode/ ~/Desktop/scicomp020/session09/lab2/
cp -ar ~/scicomp-labs-cpp-linux/pells-equation/ ~/Desktop/scicomp020/session09/lab3/
cp -ar ~/scicomp-labs-cpp-linux/pachinko-normal/ ~/Desktop/scicomp020/session09/lab4/
cp -ar ~/scicomp-labs-cpp-linux/nyquist-known/ ~/Desktop/scicomp020/session10/lab1/
cp -ar ~/scicomp-labs-cpp-linux/nyquist-unknown/ ~/Desktop/scicomp020/session10/lab2/
cp -ar ~/scicomp-labs-cpp-linux/complex-algebra/ ~/Desktop/scicomp020/session10/lab3/
cp -ar ~/scicomp-labs-cpp-linux/euler-identity/ ~/Desktop/scicomp020/session10/lab4/
cp -ar ~/scicomp-labs-cpp-linux/euler-equation/ ~/Desktop/scicomp020/session10/lab5/
cp -ar ~/scicomp-labs-cpp-linux/euler-line/ ~/Desktop/scicomp020/session10/lab6/
cp -ar ~/scicomp-labs-cpp-linux/reverse-string/ ~/Desktop/scicomp020/session11/lab1/
cp -ar ~/scicomp-labs-cpp-linux/freq-plaintext/ ~/Desktop/scicomp020/session11/lab2/
cp -ar ~/scicomp-labs-cpp-linux/freq-ciphertext/ ~/Desktop/scicomp020/session11/lab3/
cp -ar ~/scicomp-labs-cpp-linux/caesar-decrypt/ ~/Desktop/scicomp020/session11/lab4/
cp -ar ~/scicomp-labs-cpp-linux/freq-bigrams/ ~/Desktop/scicomp020/session11/lab5/
cp -ar ~/scicomp-labs-cpp-linux/anagrams-slow/ ~/Desktop/scicomp020/session11/lab6/
cp -ar ~/scicomp-labs-cpp-linux/anagrams-fast/ ~/Desktop/scicomp020/session11/lab7/
cp -ar ~/scicomp-labs-cpp-linux/anagrams-compound/ ~/Desktop/scicomp020/session11/lab8/
cp -ar ~/scicomp-labs-cpp-linux/scramble-squares/ ~/Desktop/scicomp020/session12/lab1/
cp -ar ~/scicomp-labs-cpp-linux/draw-polynomial/ ~/Desktop/scicomp020/session13/lab1/
cp -ar ~/scicomp-labs-cpp-linux/draw-monolith/ ~/Desktop/scicomp020/session13/lab2/
cp -ar ~/scicomp-labs-cpp-linux/draw-pyramid/ ~/Desktop/scicomp020/session13/lab3/
cp -ar ~/scicomp-labs-cpp-linux/draw-sphere/ ~/Desktop/scicomp020/session13/lab4/
cp -ar ~/scicomp-labs-cpp-linux/draw-torus/ ~/Desktop/scicomp020/session13/lab5/
cp -ar ~/scicomp-labs-cpp-linux/lrss-bubble/ ~/Desktop/scicomp020/session14/lab1/
cp -ar ~/scicomp-labs-cpp-linux/lrss-qsort/ ~/Desktop/scicomp020/session14/lab2/
cp -ar ~/scicomp-labs-cpp-linux/freq-substr/ ~/Desktop/scicomp020/session14/lab3/
cp -ar ~/scicomp-labs-cpp-linux/idw/ ~/Desktop/scicomp020/session14/lab4/
cp -ar ~/scicomp-labs-cpp-linux/birthday-paradox/ ~/Desktop/scicomp020/session14/lab5/
cp -ar ~/scicomp-labs-cpp-linux/projectile-motion/ ~/Desktop/scicomp020/session15/lab1/
cp -ar ~/scicomp-labs-cpp-linux/decay-fluorine18/ ~/Desktop/scicomp020/session15/lab2/
cp -ar ~/scicomp-labs-cpp-linux/decay-carbon14/ ~/Desktop/scicomp020/session15/lab3/
cp -ar ~/scicomp-labs-cpp-linux/pendulum/ ~/Desktop/scicomp020/session15/lab4/
cp -ar ~/scicomp-labs-cpp-linux/harmonograph/ ~/Desktop/scicomp020/session15/lab5/
cp -ar ~/scicomp-labs-cpp-linux/mc-circle-prng/ ~/Desktop/scicomp020/session16/lab1/
cp -ar ~/scicomp-labs-cpp-linux/mc-circle-qrng/ ~/Desktop/scicomp020/session16/lab2/
cp -ar ~/scicomp-labs-cpp-linux/mc-sphere/ ~/Desktop/scicomp020/session16/lab3/
cp -ar ~/scicomp-labs-cpp-linux/mc-hypersphere/ ~/Desktop/scicomp020/session16/lab4/
cp -ar ~/scicomp-labs-cpp-linux/mc-highdimensional/ ~/Desktop/scicomp020/session16/lab5/
cp -ar ~/scicomp-labs-cpp-linux/collatz-conjecture/ ~/Desktop/scicomp020/session16/lab6/
cp -ar ~/scicomp-labs-cpp-linux/stoichiometry/ ~/Desktop/scicomp020/session17/lab1/
cp -ar ~/scicomp-labs-cpp-linux/kmeans/ ~/Desktop/scicomp020/session17/lab2/
cp -ar ~/scicomp-labs-cpp-linux/make-samples/ ~/Desktop/scicomp020/session18/lab1/
cp -ar ~/scicomp-labs-cpp-linux/fourier-discrete/ ~/Desktop/scicomp020/session18/lab2/
cp -ar ~/scicomp-labs-cpp-linux/space-signals/ ~/Desktop/scicomp020/session18/lab3/
cp -ar ~/scicomp-labs-cpp-linux/sunspots/ ~/Desktop/scicomp020/session18/lab4/
cp -ar ~/scicomp-labs-cpp-linux/spectrum-rydberg/ ~/Desktop/scicomp020/session19/lab1/
cp -ar ~/scicomp-labs-cpp-linux/spectrum-bohr/ ~/Desktop/scicomp020/session19/lab2/
cp -ar ~/scicomp-labs-cpp-linux/complex-factorization/ ~/Desktop/scicomp020/session19/lab3/
cp -ar ~/scicomp-labs-cpp-linux/ifs-triangle/ ~/Desktop/scicomp020/session20/lab1/
cp -ar ~/scicomp-labs-cpp-linux/ifs-fern/ ~/Desktop/scicomp020/session20/lab2/
cp -ar ~/scicomp-labs-cpp-linux/ifs-bnl/ ~/Desktop/scicomp020/session20/lab3/
cp -ar ~/scicomp-labs-cpp-linux/ifs-square/ ~/Desktop/scicomp020/session20/lab4/

